### ISSUE TITLE
Missing xbox support

### ISSUE THREAD

**Issue by FLEXZICAN** [EpicKitten/PUBGLibrary#7]
First off great library, easy to use!

I was using it for a little hobby project of mine and noticed that when I tried to get a match I'd get the "Unknown enum case xbox-<region>". This is because of the way ValueForString works in the ShardIdExtensions, this function does not support xbox. Could this be added?

**Comment by EpicKitten** [comment]
Yes! I'd love to!, could you please send an Xbox Match ID I can query?

**Comment by FLEXZICAN** [comment]
Awesome! Sure, I was using this Id: cb7f201f-b756-401c-a294-098a60422c6f.

**Comment by EpicKitten** [comment]
Fixed https://github.com/EpicKitten/PUBGLibrary/commit/b80d8313294b8d64fc5401402608d698578e89fd
